//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFootballClub
{


    public partial class Contact
    {
        protected global::System.Web.UI.WebControls.TextBox txtContactName;

        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;

        protected global::System.Web.UI.WebControls.TextBox txtContactSubject;

        protected global::System.Web.UI.WebControls.TextBox txtContactMessage;

        protected global::System.Web.UI.WebControls.Button btnSend;

        protected global::System.Web.UI.WebControls.Label lblContactMessage;
    }
}
