//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFootballClub
{


    public partial class FixturesAdmin
    {

        protected global::System.Web.UI.WebControls.TextBox txtMatchDate;

        protected global::System.Web.UI.WebControls.TextBox txtTeam1;

        protected global::System.Web.UI.WebControls.TextBox txtTeam2;

        protected global::System.Web.UI.WebControls.TextBox txtStadium;

        protected global::System.Web.UI.WebControls.TextBox txtResult;

        protected global::System.Web.UI.WebControls.TextBox txtStatus;

        protected global::System.Web.UI.WebControls.Button btnAddFixture;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvFixtures;
    }
}
