//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFootballClub
{


    public partial class MatchDetails
    {

        /// <summary>
        /// BodyContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Content BodyContent;

        /// <summary>
        /// ddlFixture control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlFixture;

        /// <summary>
        /// btnLoadDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnLoadDetails;

        /// <summary>
        /// gvEvents control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvEvents;

        /// <summary>
        /// rptTimeline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptTimeline;
    }
}
