//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFootballClub
{


    public partial class NewsAdmin
    {

        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        protected global::System.Web.UI.WebControls.FileUpload fuNewsImage;

        protected global::System.Web.UI.WebControls.TextBox txtPublishDate;

        protected global::System.Web.UI.WebControls.Button btnAddNews;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvNews;
    }
}
