//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myFootballClub
{


    public partial class NewsDetails
    {

        protected global::System.Web.UI.WebControls.Panel pnlNews;

        protected global::System.Web.UI.HtmlControls.HtmlImage imgNews;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblTitle;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDate;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lblDescription;

        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        protected global::System.Web.UI.WebControls.Panel pnlComments;

        protected global::System.Web.UI.WebControls.TextBox txtCommentName;

        protected global::System.Web.UI.WebControls.TextBox txtCommentEmail;

        protected global::System.Web.UI.WebControls.TextBox txtComment;

        protected global::System.Web.UI.WebControls.Button btnSubmitComment;

        protected global::System.Web.UI.WebControls.Label lblCommentMessage;

        protected global::System.Web.UI.WebControls.Repeater rptComments;
    }
}
